# yaml-language-server: $schema=https://www.schemastore.org/github-issue-forms.json
name: "5: To Do"
description: "Use this template to track tasks."
title: "todo: "
labels: ["Kind: To Do"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a description of your tasks here.
