# yaml-language-server: $schema=https://www.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Docs
    url: https://libredirect.manerakai.com/docs.html
    about: Documentation
